export const CategoriesLib = [
  {
    categoryId: 1,
    name: "K-pop",
    slug: "k-pop",
    description: "Todo kpop en Asian All Design",
    image: "k-pop.webp",
  },
  {
    categoryId: 2,
    name: "Anime",
    slug: "anime",
    description: "Lo mejor del anime en Asian All Design",
    image: "anime.webp",
  },
  {
    categoryId: 3,
    name: "Tendencia",
    slug: "tendencia",
    description: "Las ultimas tendencias en Asian All Design",
    image: "tendencia.webp",
  },
  {
    categoryId: 4,
    name: "BTS",
    slug: "bts",
    description: "Lo mejor de BTS en Asian All Design",
    image: "bts.webp",
  },
  {
    categoryId: 5,
    name: "Black Pink",
    slug: "black-pink",
    description: "Lo mejor de Black Pink en Asian All Design",
    image: "black-pink.webp",
  },
  {
    categoryId: 6,
    name: "New Jeans",
    slug: "new-jeans",
    description: "Lo mejor de New Jeans en Asian All Design",
    image: "new-jeans.webp",
  },
  {
    categoryId: 7,
    name: "One Piece",
    slug: "one-piece",
    description: "Lo mejor de One Piece en Asian All Design",
    image: "one-piece.webp",
  },
  {
    categoryId: 8,
    name: "Twice",
    slug: "twice",
    description: "Lo mejor de Twice en Asian All Design",
    image: "twice.webp",
  },
  {
    categoryId: 9,
    name: "Le Sserafim",
    slug: "le-sserafim",
    description: "Lo mejor de Le Sserafim en Asian All Design",
    image: "le-sserafim.webp",
  },
  {
    categoryId: 10,
    name: "Super Junior",
    slug: "super-junior",
    description: "Lo mejor de Super Junior en Asian All Design",
    image: "super-junior.webp",
  },
  {
    categoryId: 11,
    name: "Seventeen",
    slug: "seventeen",
    description: "Lo mejor de Seventeen en Asian All Design",
    image: "seventeen.webp",
  },
  {
    categoryId: 12,
    name: "TXT",
    slug: "txt",
    description: "Lo mejor de TXT en Asian All Design",
    image: "txt.webp",
  },
  {
    categoryId: 13,
    name: "Nmixx",
    slug: "nmixx",
    description: "Lo mejor de Nmixx en Asian All Design",
    image: "nmixx.webp",
  },
  {
    categoryId: 14,
    name: "BabyMonster",
    slug: "babymonster",
    description: "Lo mejor de BabyMonster en Asian All Design",
    image: "babymonster.webp",
  },
  {
    categoryId: 15,
    name: "Babymetal",
    slug: "babymetal",
    description: "Lo mejor de Babymetal en Asian All Design",
    image: "babymetal.webp",
  },
  {
    categoryId: 16,
    name: "Jungkook",
    slug: "jungkook",
    description: "Lo mejor de Jeon Jung-kook (Jungkook) en Asian All Design",
    image: "jungkook.webp",
  },
  {
    categoryId: 17,
    name: "Naruto",
    slug: "naruto",
    description: "Lo mejor de Naruto en Asian All Design",
    image: "naruto.webp",
  },
  {
    categoryId: 18,
    name: "Demon Slayer",
    slug: "demon-slayer",
    description: "Lo mejor de Demon Slayer en Asian All Design",
    image: "demon-slayer.webp",
  },
  {
    categoryId: 19,
    name: "Metal",
    slug: "metal",
    description: "Lo mejor de Metal en Asian All Design",
    image: "metal.webp",
  },
  {
    categoryId: 20,
    name: "Kawaii Metal",
    slug: "kawaii-metal",
    description: "Lo mejor de Kawaii Metal en Asian All Design",
    image: "kawaii-metal.webp",
  },
  {
    categoryId: 21,
    name: "BT21",
    slug: "bt21",
    description: "Lo mejor de BT21 en Asian All Design",
    image: "bt21.webp",
  },
  {
    categoryId: 22,
    name: "BTS TinyTAN",
    slug: "bts-tinytan",
    description: "Lo mejor de BTS TinyTAN en Asian All Design",
    image: "bts-tinytan.webp",
  },
  {
    categoryId: 23,
    name: "Jimin",
    slug: "jimin",
    description: "Lo mejor de Jimin en Asian All Design",
    image: "jimin.webp",
  },
];
